### PR TITLE
fix: user action messages

### LINKED ISSUE #745: User Action Messages Missing for Topic, Announcement, or Description Changes
### Description:

User action messages for updates to the topic, description, or announcement do not display as expected in EmbeddedChat. These messages should notify users when changes are made to the room information.

### Steps to reproduce:

1. Edit the room information (topic , announcement , description ) 
2. Observe that a blank message is displayed in the chat instead of the expected user action message.

### Expected behavior:

When a user updates the room's topic, announcement, or description, a proper user action message should appear in the chat 

### Actual behavior:

[Screencast from 2024-12-28 13-52-31.webm](https://github.com/user-attachments/assets/17c50236-4b3f-4bb5-845e-c547977c74f9)

### PR DESCRIPTION
**Pull request by abirc8010**
# Brief Title

This update ensures that user action messages are displayed when the room's topic, announcement, or description is updated. Additionally, it introduces styling changes for better alignment and includes a showUsername prop in Storybook for testing.

## Acceptance Criteria fulfillment

- [ ] Added 3 new cases in the existing switch case to handle topic, announcement, and description updates.
- [ ] Styled `MessageBodyContainer` to set max-width to 90% for proper alignment

Fixes #745 

## Video/Screenshots
[Screencast from 2024-12-28 13-45-07.webm](https://github.com/user-attachments/assets/de869ca4-eba7-4b84-92bc-7e7fc14d8772)

## PR Test Details

**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-746 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

### CODE REVIEW

**Review by Spiral-Memory — APPROVED** [review]
LGTM ! Thanks @abirc8010

File: packages/react/src/views/EmbeddedChat.js [hunk 1]
```diff
@@ -279,6 +279,7 @@ EmbeddedChat.propTypes = {
   channelName: PropTypes.string,
   anonymousMode: PropTypes.bool,
   toastBarPosition: PropTypes.string,
+  showUsername: PropTypes.bool,
```
Comment (Spiral-Memory) [inline packages/react/src/views/EmbeddedChat.js:282]: Why this, in this PR?

Comment (abirc8010) [reply packages/react/src/views/EmbeddedChat.js]: removed
