### PR TITLE
[Feat/fix] Added sending state to file upload modal

### LINKED ISSUE #521: Add loading state to File upload modal
Screenshot 2024-03-17 at 5 38 08 PM

### PR DESCRIPTION
**Pull request by thesynthax**
# Brief Title
Added sending state to file upload modal

Fixes #521 

## Video/Screenshots

https://github.com/RocketChat/EmbeddedChat/assets/29705333/00303d92-b4cf-4679-9e9a-718b0d730d81

### CODE REVIEW

File: packages/react/src/components/Attachments/AttachmentWindow.js [hunk 1]
```diff
@@ -15,6 +15,8 @@ function AttachmentWindow() {
   const toggle = useAttachmentWindowStore((state) => state.toggle);
   const data = useAttachmentWindowStore((state) => state.data);
   const setData = useAttachmentWindowStore((state) => state.setData);
+  const isPending = useAttachmentWindowStore((state) => state.isPending);
```
Comment (Spiral-Memory) [inline packages/react/src/components/Attachments/AttachmentWindow.js:18]: Do we need global state here ? Why not use `useState` for this ?

File: packages/react/src/components/Attachments/AttachmentWindow.js [hunk 2]
```diff
@@ -124,13 +128,24 @@ function AttachmentWindow() {
...
                 </button>
 
-                <button
-                  type="button"
-                  onClick={submit}
-                  className={styles.attachment_window_submit_button}
-                >
-                  Send
-                </button>
+                {!isPending && (
```
Comment (Spiral-Memory) [inline packages/react/src/components/Attachments/AttachmentWindow.js:131]: Instead of code duplication, can't we use something like this ? 

```
<button
  type="button"
  onClick={submit}
  className={styles.attachment_window_submit_button}
  disabled={isPending}
>
  {isPending ? 'Sending...' : 'Send'}
</button>

```

Comment (Spiral-Memory) [reply packages/react/src/components/Attachments/AttachmentWindow.js:131]: Also it would be great if you add this css to show that button is grayed out !

```
.attachment_window_submit_button[disabled] {
  background-color: rgb(168, 176, 179);
}

```

File: packages/react/src/components/Attachments/AttachmentWindow.js (hunk 1 above)
Comment (thesynthax) [reply packages/react/src/components/Attachments/AttachmentWindow.js]: done!

**Review by Spiral-Memory — APPROVED** [review]

**Comment by Spiral-Memory** [comment]
@thesynthax Please attach a new video after these changes.

**Comment by thesynthax** [comment]
https://github.com/RocketChat/EmbeddedChat/assets/29705333/9f20c743-5651-4289-900e-be3ea8cc9af6

**Comment by Spiral-Memory** [comment]
LGTM!

**Review by sidmohanty11 — APPROVED** [review]
