### PR TITLE
fix: Addressed issues related to fetching different informations in private channels.

### LINKED ISSUE #423: [BUG] Unable to access private channel information and older chats
### Description:

The application currently cannot fetch the information of a private channel properly. The older messages are not displayed in the private channel, even for authorized users, although they can send messages. Users who are not members of the private channel can still log in, but they get logged out when trying to send a message without receiving any information on why they were logged out, resulting in an unpleasant experience.

### Steps to reproduce:

1. Set up the Rocket.Chat Server.
2. Adjust the channel permissions to private.
3. Access the embedded chat, log in, and compare the observed behavior with the expected.

### Expected behavior:

When the channel is private, only permit users who have joined or **have permission** to log in and communicate. Also, they must be able to access the **channel information and view older messages** in the chat. Additionally, **log out any unauthorised user** attempting to log in with information that suggests the channel doesn't exist or they are not allowed to join.

### Actual behavior:

For private channels, users with permission also **can't see older messages**, although they can send messages. **Users who are not members of the private channel can still log in**, but they get **logged out when trying to send a message** **without receiving any information** on why they were logged out, resulting in an unpleasant experience.

https://github.com/RocketChat/EmbeddedChat/assets/78961432/27441077-aea0-4070-ba80-28167e6f1ec5

### PR DESCRIPTION
**Pull request by Spiral-Memory**
# Brief Title
Resolved issue with fetching messages, member, channel info and roles in private channels.

## Acceptance Criteria fulfillment

- [x] Identified the bug causing inability to fetch messages in private channels. Found that the API `channels.info` was unable to retrieve private channel information. Replaced it with `rooms.info` as per Rocket Chat REST API documentation. Introduced a state variable `isChannelPrivate` which will change based on `t` property of channel information to determine which API to use for fetching messages, members, and roles based on channel privacy.

- [x] Utilized `groups.*` API instead of `channel.*`  as per the documentation when fetching messages, members, and roles to address the limitations of the former in handling private channel information.

- [x] Adjusted frontend calls accordingly to accommodate the updated API. No breaking changes introduced, as `isChannelPrivate` defaults to false.

Fixes #423 

## Video/Screenshots

https://github.com/RocketChat/EmbeddedChat/assets/78961432/abf8409d-f228-4ad2-90c3-1250869dbd64

Note: In the video, zishan.barun@gmail.com is the authorized user and ahmadzishan7277@gmail.com is the unauthorized user. This is to demonstrate the functionality of the app.

### CODE REVIEW

File: packages/react/src/components/ChatHeader/ChatHeader.js [hunk 1]
```diff
@@ -34,6 +34,8 @@ const ChatHeader = ({
   const setShowChannelinfo = useChannelStore(
     (state) => state.setShowChannelinfo
   );
+  const isChannelPrivate = useChannelStore((state)=>state.isChannelPrivate);
```
Comment (sidmohanty11) [inline packages/react/src/components/ChatHeader/ChatHeader.js:37]: can you please run prettier?

**Review by sidmohanty11 — COMMENTED** [review]
LGTM! Thanks @Spiral-Memory ! Just left a minor comment

File: packages/react/src/components/ChatHeader/ChatHeader.js (hunk 1 above)
Comment (Spiral-Memory) [reply packages/react/src/components/ChatHeader/ChatHeader.js:37]: Yaa sure, just a min

Comment (Spiral-Memory) [reply packages/react/src/components/ChatHeader/ChatHeader.js]: @sidmohanty11 , Done

**Comment by Spiral-Memory** [comment]
@sidmohanty11 , Thank you so much for your appreciation 🚀, it means a lot. I've resolved the formatting issue as you asked. You can review it and approve / merge the changes if everything looks good.

**Comment by Spiral-Memory** [comment]
@sidmohanty11 , @abhinavkrin , can either of you please merge this pull request? It has already been reviewed and i have fixed the formatting issue. I have another pull request, #421, which I have converted into a draft, as that can only be finalized after these changes are reflected. I will work on that after this, as it is dependent on this PR.

File: packages/api/src/EmbeddedChatApi.ts [hunk 2]
```diff
@@ -435,13 +435,14 @@ export default class EmbeddedChatApi {
    * fields - json object with properties that have either 1 or 0 to include them or exclude them
    * @returns messages
    */
-  async getMessages(anonymousMode = false, options: {
+  async getMessages(anonymousMode = false, isChannelPrivate = false, options: {
```
Comment (abhinavkrin) [inline packages/api/src/EmbeddedChatApi.ts:438]: This is a breaking change as you have changed the order of parameters. Add the new parameter at the last.

**Review by abhinavkrin — CHANGES_REQUESTED** [review]

File: packages/api/src/EmbeddedChatApi.ts (hunk 2 above)
Comment (Spiral-Memory) [reply packages/api/src/EmbeddedChatApi.ts:438]: @abhinavkrin , Awesome catch It might break the react native app, Just a min, let me fix it.

**Comment by Spiral-Memory** [comment]
@abhinavkrin , Fixed as per your suggestion.
