### PR TITLE
fix: update file upload to use RC 8.x rooms.media API

### LINKED ISSUE #1069: fix: update file upload to use RC 8.x rooms.media API
### Description:

File uploads fail with a 404 Not Found error when using EmbeddedChat with Rocket.Chat 8.x servers. The sendAttachment function uses the deprecated /api/v1/rooms.upload/:rid endpoint which was replaced in RC 8.x with a new two-step process using /api/v1/rooms.media/:rid and /api/v1/rooms.mediaConfirm/:rid/:fileId.

### Steps to reproduce:

1. Connect EmbeddedChat to a Rocket.Chat 8.x server
2. Log in to the chat
3. Try to upload a file (image, document, etc.) using the attachment button
4. Observe the network request failing with 404

### Expected behavior:

File should upload successfully and appear in the chat.

### Actual behavior:

Upload fails with:
POST http://localhost:3000/api/v1/rooms.upload/{roomId} 404 (Not Found)sendAttachment error: Server error 404 404 Not Found

The file is never uploaded because Rocket.Chat 8.x uses  the new rooms.media + rooms.mediaConfirm two-step process

https://github.com/user-attachments/assets/0f9b7b0b-429a-44c7-9fd2-ebfd7a0526ec

**Hoping this issue happens globally due to, hitting the old file upload endpoint**

### PR DESCRIPTION
**Pull request by dodaa08**
- Replace deprecated rooms.upload endpoint with new two-step process
- Step 1: POST to rooms.media/:rid to upload file
- Step 2: POST to rooms.mediaConfirm/:rid/:fileId to confirm with metadata
- Fixes file upload 404 error on Rocket.Chat 8.x servers

# Brief Title
fix: update file upload to use RC 8.x rooms.media API

## Acceptance Criteria fulfillment

[x] File uploads work on Rocket.Chat 8.x servers
[x] Thread attachments supported (tmid parameter)
[x] File description is properly sent
[x] Auth headers included in both requests

Fixes #1069

## Video/Screenshots

https://github.com/user-attachments/assets/8d4ad2f5-d174-4fb0-89d7-3f8328832fd5

## PR Test Details

**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-1070 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

### CODE REVIEW

**Review by Khizarshah01 — APPROVED** [review]
Tested locally.

The upload flow works correctly and the change to `rooms.media` / `rooms.mediaConfirm` behaves as expected.

One minor UX issue I noticed (**likely unrelated to this PR**): after sending an image, selecting the same file again does not trigger the upload flow. This seems related to the file input value not being reset after upload.

LGTM 👍

**Comment by dodaa08** [comment]
> Tested locally.
> 
> The upload flow works correctly and the change to `rooms.media` / `rooms.mediaConfirm` behaves as expected.
> 
> One minor UX issue I noticed (**likely unrelated to this PR**): after sending an image, selecting the same file again does not trigger the upload flow. This seems related to the file input value not being reset after upload.
> 
> LGTM 👍


https://github.com/user-attachments/assets/41d32b60-b303-411b-9ee8-92f8ab9bda96



hoping this work fine now

**Comment by dodaa08** [comment]
> > Tested locally.
> > The upload flow works correctly and the change to `rooms.media` / `rooms.mediaConfirm` behaves as expected.
> > One minor UX issue I noticed (**likely unrelated to this PR**): after sending an image, selecting the same file again does not trigger the upload flow. This seems related to the file input value not being reset after upload.
> > LGTM 👍
> 
>  Screencast.From.2026-01-17.22-04-57.mp4 
> hoping this work fine now

Finally Checks are passing

**Review by Khizarshah01 — APPROVED** [review]
LGTM 👍

**Comment by dodaa08** [comment]
Hi @Spiral-Memory , Let me know if anything else needed here, whenever you get to review

File: packages/api/src/EmbeddedChatApi.ts [hunk 1]
```diff
@@ -1056,26 +1056,55 @@ export default class EmbeddedChatApi {
...
       const { userId, authToken } = (await this.auth.getCurrentUser()) || {};
-      const form = new FormData();
-      if (threadId) {
-        form.append("tmid", threadId);
+      if (!userId || !authToken) {
+        console.error("sendAttachment: User not authenticated");
+        return;
       }
+
+      // Step 1: Upload file to rooms.media endpoint (RC 8.x)
```
Comment (Spiral-Memory) [inline packages/api/src/EmbeddedChatApi.ts]: Remove comments

**Review by Spiral-Memory — APPROVED** [review]
LGTM

**Comment by dodaa08** [comment]
Hey @Spiral-Memory , It was one of my early PR in RC 🫠, didn't notice I left comments in code, I have removed them, let me know if anything else is needed once you review, thanks!

**Review by Spiral-Memory — APPROVED** [review]
