### PR TITLE
Fix: Disable hover effect for User Action Messages

### LINKED ISSUE #794: Bug: Disable hover effect for User Action Messages
### Description:
After hovering over User Action Messages, we can see an effect where the background color darkens or lightens depending on whether dark or light mode is active. However, if you observe the same in Rocket.Chat, you will not see this effect for User Action Messages.

### Steps to reproduce:

1. Log in
2. Hover over User Action Messages (User Action Messages are messages that describe actions taken by users, such as "User pinned a message," "User removed a message," or "User joined the channel").

### Expected behavior:
Video From Rocket.Chat:

https://github.com/user-attachments/assets/0f56d04f-8047-4eac-b380-563b2cc051bf

### Actual behavior:
Video From Embedded Chat:

https://github.com/user-attachments/assets/a1f81845-5762-4848-88af-03eea3b36028

### PR DESCRIPTION
**Pull request by dhairyashiil**
# Brief Title
Disable the hover effect for User Action Messages

## Acceptance Criteria fulfillment

- [X] The hover effect for User Action Messages is removed.
- [X] Ensure the background color remains unaffected in both light and dark modes when hovering over User Action Messages.
- [X] Verify that the changes do not impact other message types in the chat interface.

Fixes #794

## Video/Screenshots

https://github.com/user-attachments/assets/9fdb099d-7b35-4830-82a3-1eaf78a735cd

## PR Test Details

**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-795 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

### CODE REVIEW

File: packages/react/src/views/Message/Message.js [hunk 1]
```diff
@@ -72,8 +74,23 @@ const Message = ({
   }));
 
   const isMe = message.u._id === authenticatedUserId;
+
   const theme = useTheme();
+  const { mode } = useTheme();
   const styles = getMessageStyles(theme);
+  const hasType = Boolean(message.t);
```
Comment (Spiral-Memory) [inline packages/react/src/views/Message/Message.js:81]: What about attachments ? I don't remember exactly if attachment has t or not

Comment (dhairyashiil) [reply packages/react/src/views/Message/Message.js:81]: Hey Zishan, attachments don’t have a `t` property, and I checked the code base to make sure this is correct. 

Even if a user does something with the attachment (like pinning it), this method still works. You can see in the video below where I pinned different types of attachments (audio, video, text file, image), and it worked fine.


https://github.com/user-attachments/assets/6b79d24a-bd30-4ac5-83f4-338f1966f6d2
