### PR TITLE
fix: Added avatar in thread message

### LINKED ISSUE #920: fix: Add avatar in thread messages, and format thread title
### Description:
Improving the message box which is forming thread.

### Steps to reproduce:

1. go to any message
2. Reply on thread only shows number of participants does not show their avatar

### Expected behavior:

Image

### Actual behavior:

Image

### PR DESCRIPTION
**Pull request by thepiyush-303**
# Brief Title
Format the thread message header and add avatar of the thread-creating user.

Edited: when a message is set to reply in thread the message box does not show the 'Icon' of the user who create that thread, and it also lacks some more features:
- when we form a thread reply then the main message in chat header is not formatted It is shown below in videos.
- showing tooltips when hovered on that icons.
- also previously the actual time was not shown in that message box.

## Acceptance Criteria fulfillment

- [x] Add avatar.
- [x] format text.
- [x] improve time format.
- [x] add tooltip

Fixes #920 

## Video/Screenshots
Before:

https://github.com/user-attachments/assets/f087b1b9-d6fb-4bd6-b83a-834a4d735443

After:

https://github.com/user-attachments/assets/68c96661-fd7d-4648-a749-65dab62f9d15

## PR Test Details

**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-921 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

### CODE REVIEW

**Comment by abirc8010** [comment]
Hey @thepiyush-303 , please update your PR description by adding a video , also could you please show me how it behaves if more than 2 users are involved in a thread ?

**Comment by thepiyush-303** [comment]
I will add 'video' once i have commit some more changes, if you want to see the changes then look into the issue I have attached screenshot their.

**Comment by abirc8010** [comment]
>I will add 'video' once i have commit some more changes

To avoid any confusion, could you please convert your PR into a draft if it's not yet ready for review?

>if you want to see the changes then look into the issue I have attached screenshot their.

Yes but that is for one user but what happens when there are more than two users? It might be better not to display all the avatars. For instance, in Rocket.Chat, if four users are involved in a thread, it displays the avatars of two users followed by "+2"

**Comment by thepiyush-303** [comment]
Now it is complete,
> in Rocket.Chat, if four users are involved in a thread, it displays the avatars of two users followed by "+2" 

yes, I have made changes as to show only one userAvatar who creates thread message.

**Comment by Spiral-Memory** [comment]
Hi @thepiyush-303 
Please update the description with a video, I am marking it a draft PR for now

Thanks

**Comment by thepiyush-303** [comment]
Hey @Spiral-Memory,
I have already added video of my changes in description.

**Comment by Spiral-Memory** [comment]
Hi @thepiyush-303 
Please use mp4 formats for the video, so it is visible directly

Also, update your PR description accordingly, i didn't really understand the change.

**Comment by thepiyush-303** [comment]
@Spiral-Memory 
can you now please check the description.

**Comment by Spiral-Memory** [comment]
Yaa looks good, thanks

File: packages/react/src/views/ChatHeader/ChatHeader.js [hunk 1]
```diff
@@ -423,7 +420,7 @@ const ChatHeader = ({
       </Box>
       {isThreadOpen && (
         <DynamicHeader
-          title={threadTitle}
+          title={threadMainMessage}
```
Comment (Spiral-Memory) [inline packages/react/src/views/ChatHeader/ChatHeader.js:432]: Will it can truncate after the message limit exceeds the size of a single line ?

File: packages/react/src/views/Message/MessageMetrics.js [hunk 2]
```diff
@@ -25,6 +29,16 @@ export const MessageMetrics = ({
...
 
+  const { RCInstance } = useContext(RCContext);
+
+  const getUserAvatarUrl = (username) => {
+    const host = RCInstance.getHost();
+    return `${host}/avatar/${username}`;
+  };
+
+  const participantsList =
+    message.replies.length - 1 > 0 ? `+${message.replies.length - 1}` : null;
```
Comment (Spiral-Memory) [inline packages/react/src/views/Message/MessageMetrics.js]: Add optional chaining (?.),

**Comment by thepiyush-303** [comment]
@Spiral-Memory 
Done.

**Review by Spiral-Memory — APPROVED** [review]

**Comment by Spiral-Memory** [comment]
Hi @thepiyush-303 

Doesn't look aligned 

image

**Comment by thepiyush-303** [comment]
@Spiral-Memory 


image
