### PR TITLE
Trim Whitespaces in Username/Email Fields in EmbeddedChat Login Form

### LINKED ISSUE #656: Whitespace in Username/Email Input Prevents Login in EmbeddedChat Login Form
### Description:
When logging in through the EmbeddedChat form, if extra whitespaces are added to the beginning or end of the username or email, the system doesn’t trim these whitespaces. This causes the login to fail, even though the credentials are otherwise correct.

### Steps to reproduce:

1. Go to the EmbeddedChat login form.
2. Enter a valid username or email, but include leading or trailing whitespaces.
3. Attempt to log in.

https://github.com/user-attachments/assets/1b9af213-686f-49b7-8945-a04624846140

From the above video it is clear that password's allow whitespaces along with text but the same is not allowed with username or email
so i shall not trim the password input box

### Expected behavior:
The system should automatically trim any whitespaces from the beginning or end of the username or email, allowing the login attempt to proceed if the credentials are correct.

### Actual behavior:
The system does not trim whitespaces, causing a login failure.

https://github.com/user-attachments/assets/1b47c6c1-3c7f-4dec-a5ce-515e0659530f

### Reason for Trimming Whitespaces:
- **Prevents Accidental Login Failures**: Users often accidentally add spaces before or after their input, especially on mobile devices. Trimming removes these unintended spaces, reducing the chance of failed login attempts due to formatting issues.
- **Aligns with User Expectations**: Most applications already trim whitespaces, so users typically expect that accidental spaces won’t affect their login.

### PR DESCRIPTION
**Pull request by SinghaAnirban005**
# Brief Title
Trim Whitespaces in Username/Email Fields in EmbeddedChat Login Form

## Acceptance Criteria Fulfillment

- [x] Task 1: Add logic to trim whitespaces in username/email fields on login form submission.
- [x] Task 2: Test and verify that users can log in successfully even with accidental spaces.

Fixes #656 

## Video/Screenshots

https://github.com/user-attachments/assets/5303abd9-294c-4b1f-a697-5d0b8841eaba

I did not trim for passwords because while registering on rocket chat , they allow having whitespaces after some `password` has been written

## PR Test Details
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-<pr_number> after approval.

### CODE REVIEW

**Comment by Spiral-Memory** [comment]
Here's a corrected version:

@sidmohanty11 , what do you think? Is this necessary?

**Comment by Spiral-Memory** [comment]
@sidmohanty11 , what do you think? Is this necessary?

**Comment by devanshkansagra** [comment]
Yeah I also agree with @Spiral-Memory, why would someone add whitespaces in username/email?

**Comment by Spiral-Memory** [comment]
He might be considering that, in case of a mistake while typing emails, any extra whitespace would be trimmed automatically, as some websites implement such features. However, I need to confirm this with Sidharth, since it's not strictly necessary, and there could be issues with this feature

**Comment by sidmohanty11** [comment]
I think this is a good addition

File: packages/react/src/views/LoginForm/LoginForm.js [hunk 1]
```diff
@@ -52,7 +52,7 @@ export default function LoginForm() {
   };
 
   const handleEdituserOrEmail = (e) => {
-    setUserOrEmail(e.target.value);
+    setUserOrEmail(e.target.value.trim());
```
Comment (Spiral-Memory) [inline packages/react/src/views/LoginForm/LoginForm.js:55]: @SinghaAnirban005  When we set the credential object and use the .trim() function there, why do we need it here as well?

Comment (SinghaAnirban005) [reply packages/react/src/views/LoginForm/LoginForm.js:55]: You’re absolutely right since I’ve already used .trim() when setting the credentials object, additional trimming is unnecessary. Thanks for the catch !!

**Review by Spiral-Memory — APPROVED** [review]

**Comment by Spiral-Memory** [comment]
LGTM! 
Thanks for the addition @abirc8010
