### PR TITLE
Fix: deletion of message get simultaneously deleted from the starred modal.

### LINKED ISSUE #965: Deleted starred Message in the main Chat interface  do appears in starred modal
### Description:

when the starred message is deleted from the main chat interface, it do not get deleted from the starred modal.
### Steps to reproduce:

1. Delete any starred message from the main chat interface.
2. the same message do not get deleted from the modal.

### Expected behavior:

the message do not get deleted from the starred modal interface.

### Actual behavior:

https://github.com/user-attachments/assets/cad00ffc-e0d9-413d-a255-ac2e40b3d6f4

### PR DESCRIPTION
**Pull request by smritidoneria**
# Brief Title

deletion of the starred message from the main chat interface gets deleted from the starred modal.

Fixes #965

## Video/Screenshots

https://github.com/user-attachments/assets/3bd4eb9d-a82a-4673-8f40-605d59e3cec1

## PR Test Details

**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-<pr_number> after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

### CODE REVIEW

File: packages/react/src/views/FileMessage/FileMessage.js [hunk 1]
```diff
@@ -75,6 +83,19 @@ const FileMessage = ({ fileMessage }) => {
     },
     [messages, RCInstance, dispatchToastMessage]
   );
+  useEffect(() => {
```
Comment (Spiral-Memory) [inline packages/react/src/views/FileMessage/FileMessage.js:86]: Why it is here ? Related with files ?

**Comment by smritidoneria** [comment]
Hey @Spiral-Memory , Actually there were similar issue related to the deletion of files from the sidebar, so I fixed that issue too in this pr only.

**Comment by smritidoneria** [comment]
Reference-
https://github.com/user-attachments/assets/df16a8a4-bb75-4275-b777-cd33f0616705
