### PR TITLE
Fix bug Store user's info if not present or if not same user 

### LINKED ISSUE #72: Store user's info if not present or if not same user
### Description:
https://github.com/RocketChat/EmbeddedChat/pull/51 solves it partially by adding a `me` call to the API when there is no user info stored in our localstorage but if the user changed its cookies into a new user's cookies he will still get his user profile image as the previous one and also the app would show indeterministic UI.

### Steps to reproduce:

> Note: During development only!
1. Login into EmbeddedChat
2. Login into some other account in RC
3. Come back to see in EC that you have the same profile image as before but you message with the user you logged in with in RC.

### Expected behavior:

User details should get updated

### Actual behavior:

They don't.

### Extra
You can take help of this [PR](https://github.com/RocketChat/EmbeddedChat/pull/51) to get everything working if user's info is missing and add into it a functionality to check if the user has been changed midway! This could be possible if we add a check to user_id cookie to a stored version at localstorage or if you have an amazing way, please feel free to post it here!

### PR DESCRIPTION
**Pull request by VipinDevelops**
# Fixed the bug Store user's info if not present or if the not same user 

## Acceptance Criteria fulfillment
This PR fixes an issue where the user's avatar URL and username were not being updated correctly when the user changes midway.

Fixes #72 
Closes #51 

To fix this issue, I added a new piece of state called userId to the useUserStore hook and a setter function called setUserId to update the value of userId in the store. I also added a check to compare the rc_uid cookie with the userId stored in local storage, and if these values do not match, I made a call to the me function to get the updated user information and used the setUserId and setUsername functions to update the component's state with the new values.

## Video/Screenshots
[Screencast from 2023-01-01 14-21-35.webm](https://user-images.githubusercontent.com/99081689/210165601-266978cf-872a-4ba9-9a62-c81c45e3b4fd.webm)

### CODE REVIEW

**Comment by Ak-Shaw** [comment]
I guess the last commit was made before you saw my comment on #71 👇🏻 

https://github.com/RocketChat/EmbeddedChat/pull/71#issuecomment-1367416885

Do try to follow the standard conventions, as it helps in proper communication and DevX.

Also, I'll highly encourage you to add scopes, if possible, in every commit message. It further helps to understand the changes being pushed.

**Comment by sidmohanty11** [comment]
@VipinDevelops Great work!

File: src/store/userStore.js [hunk 1]
```diff
@@ -1,6 +1,11 @@
 import create from 'zustand';
 
 const useUserStore = create((set) => ({
+  userId: localStorage.getItem('userId') || '',
```
Comment (sidmohanty11) [inline src/store/userStore.js:4]: can we change it to -> `rc_uid` ? Also can you take all the keyed items and make them as a constant and export it from a file called `constant.js` inside lib?

Something like,
```
export const RC_LOCAL_USER_ID = 'rc_uid'
export const RC_LOCAL_USER_NAME = 'rc_uname'
```
and use them everywhere instead of hardcoded strings, this will surely help us in the long run

**Comment by VipinDevelops** [comment]
Sorry @Ak-Shaw  i forgot this time but definitely will not repeat this mistake

**Review by sidmohanty11 — CHANGES_REQUESTED** [review]

**Comment by VipinDevelops** [comment]
Thank for appreciating @sidmohanty11  
This PR looks good to merge?

File: src/store/userStore.js (hunk 1 above)
Comment (VipinDevelops) [reply src/store/userStore.js:4]: Yeah sure 😊

Comment (VipinDevelops) [reply src/store/userStore.js]: you want me to use 
`export const RC_LOCAL_USER_ID = 'rc_uid';
export const RC_LOCAL_USER_NAME = 'rc_uname';
export const RC_LOCAL_USER_AVATAR_URL = 'rc_avatar_url';
export const RC_LOCAL_USER_TOKEN = 'rc_token';
`
these in every single file of whole project ?

**Comment by VipinDevelops** [comment]
I tried using constants in MessageList.js file but got an error 
image

**Comment by VipinDevelops** [comment]
i fixed the error by adding ` "parser": "@babel/eslint-parser"` and installing its dependencies

**Comment by VipinDevelops** [comment]
I have replaced all instances of 'rc_local_user_id' with 'rc_uid' and all instances of 'rc_local_user_name' with 'rc_uname'. I have also created a file called 'constant.js' inside the 'lib' folder and exported the constants 'RC_LOCAL_USER_ID' and 'RC_LOCAL_USER_NAME' from it. These constants can now be used instead of hardcoded strings throughout the codebase. This will help ensure consistency and make it easier to maintain the code in the long run. Please let me know if you have any further questions or need any further assistance.

File: src/store/userStore.js (hunk 1 above)
Comment (sidmohanty11) [reply src/store/userStore.js]: I think `LOCAL` must be used when we are storing something locally (in this case, localstorage). But we aren't storing rc_token and rc_uid

so we can have,
```
RC_USER_TOKEN_COOKIE='rc_token'
RC_USER_ID_COOKIE='rc_uid'
```

and for the rc_uid that we are storing keep it,
`RC_LOCAL_USER_ID`

so where we are using localstorage to access userid, use -> LOCAL_USER_ID but where we are using the cookie -> use the cookie string

File: src/index.js [hunk 2]
```diff
@@ -41,12 +42,52 @@ export const RCComponent = ({
...
+      setAuthenticatedUserId(res.userId);
+    }
+
+    const cookiesPresent =
+      Cookies.get(RC_LOCAL_USER_TOKEN) && Cookies.get(RC_LOCAL_USER_ID);
+    if (cookiesPresent) {
+      setIsUserAuthenticated(true);
+    }
+
+    const storedUserId = localStorage.getItem('userId');
```
Comment (sidmohanty11) [inline src/index.js:78]: change it to `rc_uid` -> RC_LOCAL_USER_ID so you don't use wrong keys

File: src/index.js [hunk 3]
```diff
@@ -41,12 +42,52 @@ export const RCComponent = ({
...
+  useEffect(() => {
+    async function getUserEssentials() {
+      const res = await RCInstance.me();
+      setAuthenticatedUserAvatarUrl(res.avatarUrl);
+      setAuthenticatedUserUsername(res.username);
+      setAuthenticatedUserId(res.userId);
+    }
+
+    const cookiesPresent =
+      Cookies.get(RC_LOCAL_USER_TOKEN) && Cookies.get(RC_LOCAL_USER_ID);
```
Comment (sidmohanty11) [inline src/index.js:73]: cookies should not be local, change them to RC_USER_TOKEN_COOKIE ...

**Review by sidmohanty11 — CHANGES_REQUESTED** [review]

**Comment by VipinDevelops** [comment]
I made the requested change please review it

File: src/index.js (hunk 3 above)
Comment (VipinDevelops) [reply src/index.js]: Done

File: src/index.js (hunk 2 above)
Comment (VipinDevelops) [reply src/index.js]: Done

File: src/components/MessageList/MessageList.js [hunk 4]
```diff
@@ -1,3 +1,4 @@
+/* eslint-disable no-underscore-dangle */
```
Comment (sidmohanty11) [inline src/components/MessageList/MessageList.js:1]: Why?

**Review by sidmohanty11 — CHANGES_REQUESTED** [review]

File: src/components/MessageList/MessageList.js (hunk 4 above)
Comment (VipinDevelops) [reply src/components/MessageList/MessageList.js:1]: i added  "parser": "@babel/eslint-parser" and  its dependencies 
 then i was getting  a error Unexpected dangling '_' in '_id'.eslint[no-underscore-dangle](https://eslint.org/docs/rules/no-underscore-dangle)   
to fix that issue I added this comment this error usually occurs when you are using an underscore (_) at the beginning of a variable or property name, which is a naming convention that is generally discouraged in JavaScript.

screenshot:
image

Comment (VipinDevelops) [reply src/components/MessageList/MessageList.js:1]: i saw one comment in ChatBody>ChatBody.js file ` /* eslint-disable no-shadow */  `so i thought its ok to add those comments in file to fix this linting error

**Comment by VipinDevelops** [comment]
Is there anything else left to fix @sidmohanty11   ?

File: src/index.js [hunk 5]
```diff
@@ -41,12 +46,52 @@ export const RCComponent = ({
...
   useEffect(() => {
-    const cookiesPresent = Cookies.get('rc_token') && Cookies.get('rc_uid');
+    const cookiesPresent =
+      Cookies.get(RC_USER_TOKEN_COOKIE) && Cookies.get(RC_USER_ID_COOKIE);
     if (cookiesPresent) {
       setIsUserAuthenticated(true);
     }
   }, []);
 
+  const authenticatedUserUsername = useUserStore((state) => state.username);
```
Comment (sidmohanty11) [inline src/index.js:56]: I was thinking about this part, and as you can see that this has bloated our index.js file with all the useUserStore hooks -> can we shift it to a generic custom hook? Something like -> `useUser`

The idea is to reuse the functionality in logout too where we destroy the local stores.
Refer:
https://github.com/RocketChat/EmbeddedChat/blob/a8d8ad31e65c752b31fc87f62ee33b385cb2d234/src/components/ChatHeader/ChatHeader.js#L35

We could handle all these logic there and keep it simple inside index.js file

**Review by sidmohanty11 — CHANGES_REQUESTED** [review]
Everything else looks fine to me

File: src/index.js (hunk 5 above)
Comment (VipinDevelops) [reply src/index.js:56]: I got your point you want to refractor that code little bit but i am not so good with react and react hooks 😅i am more of a backend guy 

Can you explain me this hook thing bit more or point me to some resources or reference please that will help alot

Comment (VipinDevelops) [reply src/index.js]: I made the useUser hook and also used that in all files where useUserstore was used before and I also added Eslint comments `/* eslint-disable no-shadow */ `  ,  ` /* eslint-disable no-nested-ternary */
` 
 to fix the error in Chatbody , Chatinput ,useUser hook

Comment (VipinDevelops) [reply src/index.js]: Please have a look @sidmohanty11  and let me know if any changes required

File: src/components/MessageList/MessageList.js (hunk 4 above)
Comment (VipinDevelops) [reply src/components/MessageList/MessageList.js:1]: image

it's showing a linting error on messages, anonymousmode  that 'messages' is already declared in the upper scope

File: src/index.js (hunk 5 above)
Comment (VipinDevelops) [reply src/index.js]: I researched about it for you Linting is the process of running a program that analyzes your code for potential errors or issues. It can help you find syntax errors, undefined variables, and other issues that can cause problems when you try to run your code. Linting can be a useful tool for catching errors early on and improving the overall quality of your code.

Linting forces us to Coding conventions are guidelines that recommend how you should format and organize your code. These conventions can include things like how you should name variables, where you should put whitespace, and how you should structure your code. Coding conventions are used to make code more consistent and easier to read and if some file is already written without following this convention we could add a comment telling eslint to ignore conventions for this file or this line

Comment (sidmohanty11) [reply src/index.js]: What?

**Comment by sidmohanty11** [comment]
Can you please revert your changes (the useUser part).

File: src/index.js (hunk 5 above)
Comment (VipinDevelops) [reply src/index.js]: i mean i know why we are using this comments because of linting

**Comment by VipinDevelops** [comment]
Done

File: src/index.js [hunk 6]
```diff
@@ -41,12 +46,52 @@ export const RCComponent = ({
...
+    const storedUserId = localStorage.getItem(RC_LOCAL_USER_ID);
+    const currentUserId = Cookies.get(RC_USER_ID_COOKIE);
+    if (
+      !authenticatedUserUsername ||
+      !authenticatedUserAvatarUrl ||
+      !authenticatedUserId ||
+      storedUserId !== currentUserId
+    ) {
+      getUserEssentials();
+      localStorage.setItem(RC_LOCAL_USER_ID, currentUserId);
```
Comment (sidmohanty11) [inline src/index.js:91]: redundant

File: src/index.js [hunk 7]
```diff
@@ -41,12 +46,52 @@ export const RCComponent = ({
...
+      setAuthenticatedUserId(res.userId);
+    }
+
+    const cookiesPresent =
+      Cookies.get(RC_USER_TOKEN_COOKIE) && Cookies.get(RC_USER_ID_COOKIE);
+    if (cookiesPresent) {
+      setIsUserAuthenticated(true);
+    }
+
+    const storedUserId = localStorage.getItem(RC_LOCAL_USER_ID);
```
Comment (sidmohanty11) [inline src/index.js:82]: redundant, we are already getting the `authenticatedUserId`

**Comment by VipinDevelops** [comment]
I also tested the current changes on my local system everything is working fine

File: src/index.js (hunk 5 above)
Comment (sidmohanty11) [reply src/index.js:56]: I know its because of linting :( not sure what you mean

**Review by sidmohanty11 — CHANGES_REQUESTED** [review]

**Comment by VipinDevelops** [comment]
Done i removed redundant code

File: src/index.js (hunk 7 above)
Comment (VipinDevelops) [reply src/index.js]: i removed it

File: src/index.js (hunk 5 above)
Comment (VipinDevelops) [reply src/index.js:52]: no worries i removed the redundant code and checked everything running fine

**Comment by VipinDevelops** [comment]
hey @sidmohanty11  can you please review the changes

**Review by sidmohanty11 — COMMENTED** [review]
@VipinDevelops PTAL at the merge conflicts, else looks fine to me

**Comment by VipinDevelops** [comment]
@sidmohanty11  i resolved the conflict please have a look

**Comment by VipinDevelops** [comment]
Hey @sidmohanty11  can you please review and merge this PR soon its been a week i am working on this same issue after this i am planning to start working on TOTP issue so please 🙏

**Comment by VipinDevelops** [comment]
Hi @sidmohanty11 
Could you please review my pull request as soon as possible? I would really appreciate it if you could expedite the review process and merge the PR as soon as possible.

Thank you in advance for your help.

**Comment by sidmohanty11** [comment]
I'm so sorry for the delay, I was really caught up with my exams. Thanks for your patience @VipinDevelops . Again, thanks a lot for this contribution.🥳

**Review by sidmohanty11 — APPROVED** [review]
LGTM!

**Comment by VipinDevelops** [comment]
no problem at all! I completely understand how hectic exams can be
