### PR TITLE
Fix: Editing of Audio, Video and File Message

### LINKED ISSUE #696: Audio message edit functionality sends a new message instead of editing the existing one
### Description:

When a user sends a audio message in the chat and clicks on the "Edit" option, they can record another video. However, instead of editing the existing message, the application sends a new message with the newly recorded audio.

### Steps to reproduce:

1.Send a audio message in the chat.
2. Click on the "Edit" option for the audio message.
3.Record another audio and confirm the edit.
4. Observe that instead of editing the existing message, a new message is sent with the updated audio.

### Expected behavior:

The existing audio message should be updated with the newly recorded audio when edited.

### Actual behavior:

A new message is sent with the updated audio instead of editing the existing one.

https://github.com/user-attachments/assets/6e7331a0-6446-465c-bfd7-dfdc3867689a

### LINKED ISSUE #698: BUG: Edit functionality for Video Message sends a new message
### Description:

When a user sends a video message in the chat and clicks on the "Edit" option, they can record another video. However, the User should not be able to edit video messages. Instead, they can delete the message and send a new one

### Steps to reproduce:

1. Send a video message in the chat.
2. Click on the "Edit" option for the video message.
3. Now, the User can record another video and confirm the edit.
4. Observe that instead of denying to edit the message, a new message is sent with the updated audio.

### Expected behavior:
The User should not be able to edit video messages. Instead, they can delete the message and send a new one

### Actual behavior:
A new message is sent with the updated video instead of denying to edit the message. 

https://github.com/user-attachments/assets/f11ff81a-572a-442f-9a03-6e7d5d619471

### PR DESCRIPTION
**Pull request by dhairyashiil**
# Brief Title
Updated handleEditMessage functionality, and added validation for audio, video, and file message

When a user sends an audio/video/file message in the chat and clicks on the "Edit" option, they can record another audio or video/upload new file. However, the User should not be able to edit audio or video, or file messages. Instead, they can delete the message and send a new one

## Acceptance Criteria fulfillment

- [x] When the user attempts to edit an audio/video/file message, a popup will appear stating 'Editing Audio/Video/File messages is not supported at the moment.''

Fixes #696
Fixes #698

## Screenshots
Screenshot (1448)
and
Screenshot (1450)

## PR Test Details

**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-697 after approval.

### CODE REVIEW

**Comment by devanshkansagra** [comment]
Hey @dhairyashiil, can you tell me why you are showing popup of not supported error rather than achieving expected behaviour mentioned by @smritidoneria in issue #696?

**Comment by smritidoneria** [comment]
Instead of showing the error, it's better to hide the option of edit for the audio/ video message.
What do you think @Spiral-Memory

**Comment by Spiral-Memory** [comment]
Yes better

**Comment by devanshkansagra** [comment]
But I think it will be difficult

> Instead of showing the error, it's better to hide the option of edit for the audio/ video message. What do you think @Spiral-Memory

Not only for audio / video but all types of attachments -> audio, video and file

**Comment by abirc8010** [comment]
> Not only for audio / video but all types of attachments -> audio, video, file and image

I think for files , images we can keep the edit option to edit the file description as in RC

**Comment by smritidoneria** [comment]
> > Not only for audio / video but all types of attachments -> audio, video, file and image
> 
> I think for files , images we can keep the edit option to edit the file description as in RC

I think this is better

**Comment by dhairyashiil** [comment]
Hello Zishan (@Spiral-Memory), I have changed my approach from showing a popup to hiding the 'edit' option for audio/video messages.

Thank you, Abir (@abirc8010) and Smriti (@smritidoneria) for your comments. At first, I thought of hiding the 'edit' option for all messages except text, but because of your comments, I understood that this is the better approach.

Video: 
We cannot edit audio and video messages, but we can update the descriptions of both file and image messages.

https://github.com/user-attachments/assets/c1abe1ac-745c-4831-a7a8-f7e3e5802a38

File: packages/react/src/views/Message/MessageToolbox.js [hunk 1]
```diff
@@ -120,7 +120,7 @@ export const MessageToolbox = ({
         id: 'edit',
         onClick: () => handleEditMessage(message),
         iconName: 'edit',
-        visible: message.u._id === authenticatedUserId,
+        visible: (message.u._id === authenticatedUserId) && (message.files?.[0].type !== 'audio/mpeg') && (message.files?.[0].type !== 'video/mp4'),
```
Comment (Spiral-Memory) [inline packages/react/src/views/Message/MessageToolbox.js:123]: But not all audio and video are in MPEG/MP4 format, right?

We might need to create a mapping for suitable formats and then try

**Comment by abirc8010** [comment]
I think instead of completely removing the edit option , we can disable the audio, video and file option in editing mode like in RC.
So that user can edit description.

**Comment by Spiral-Memory** [comment]
> I think instead of completely removing the edit option , we can disable the audio, video and file option in editing mode like in RC. So that user can edit description.

Yes better!

File: packages/react/src/views/Message/MessageToolbox.js (hunk 1 above)
Comment (dhairyashiil) [reply packages/react/src/views/Message/MessageToolbox.js:123]: Hello Zishan, Currently all our audios are of type: 'audio/mpeg' & videos are of type: 'video/mp4'

These values are hardcoded in the 'AudioMessageRecorder.js' and 'VideoMessageRecoder.js' files.

image

image


So, I think the above condition will work for all audio and video files since we currently have only one format. 

If we later introduce new formats for audio and video, we will update this logic accordingly.

Comment (Spiral-Memory) [reply packages/react/src/views/Message/MessageToolbox.js:123]: Okay, this is only for the audio and video message recorded directly ? 

And not for the file sent ?

**Comment by Spiral-Memory** [comment]
Please resolve the conflict

**Comment by dhairyashiil** [comment]
> I think instead of completely removing the edit option , we can disable the audio, video and file option in editing mode like in RC. So that user can edit description.

Hello Abir, right now I have not disabled edit option for files, user can still edit description for file messages. 

Currently, our Embedded Chat approach is slightly different for audio and video scenarios than RC.
In RC while recording and sending audio and video messages, we give description as well But it is not the same for Embedded. 

Screenshots from RC-
For Audio:
image

For Video:
image

On Embedded we directly send the audio and video messages, without asking for a description.

File: packages/react/src/views/Message/MessageToolbox.js (hunk 1 above)
Comment (dhairyashiil) [reply packages/react/src/views/Message/MessageToolbox.js:123]: Yes, Correct.

**Comment by dhairyashiil** [comment]
> Please resolve the conflict

Yes, Zishan. resolving now

**Comment by dhairyashiil** [comment]
Hello Zishan (@Spiral-Memory), resolved the conflict and format check issue. 

since it's my first PR I apologize for any inconvenience caused by my lack of experience, do give me a review so that I can make better PRs

**Comment by Spiral-Memory** [comment]
No worries @dhairyashiil

File: packages/react/src/views/Message/MessageToolbox.js [hunk 2]
```diff
@@ -130,7 +130,10 @@ export const MessageToolbox = ({
         id: 'edit',
         onClick: () => handleEditMessage(message),
         iconName: 'edit',
-        visible: isAllowedToEditMessage,
+        visible:
+          isAllowedToEditMessage &&
+          message.files?.[0].type !== 'audio/mpeg' &&
```
Comment (Spiral-Memory) [inline packages/react/src/views/Message/MessageToolbox.js:135]: Instead of checking here directly, make a variable for this check and use it here.

**Review by Spiral-Memory — APPROVED** [review]

File: packages/react/src/views/Message/MessageToolbox.js (hunk 2 above)
Comment (dhairyashiil) [reply packages/react/src/views/Message/MessageToolbox.js]: Done. Thank you, Zishan.

**Review by Spiral-Memory — APPROVED** [review]
