### PR TITLE
Fix thread title for files and  messages in report modal

### LINKED ISSUE #625: Thread Title Not Visible When Starting Thread at File Messages and  Messages are not Visible in Report Modal
### Description:

The thread title is not visible when initiating the thread at files.
while reporting any message inside the thread, the message in the report modal is not visible

### Steps to reproduce:

1. go to Chat section and upload a file
2. Make a thread of a file, no title for thread
3.Try reporting any message in the thread, message to which the user is reporting is not visible in the thread modal.

### Expected behavior:

Thread title should be visible always either it is a file or message.
Message should be visible in the report model.

### Actual behavior:

https://github.com/user-attachments/assets/09c5b884-4076-498e-868e-8b76cb699d5a

### PR DESCRIPTION
**Pull request by smritidoneria**
# Brief Title

This pr demonstrates the visibility of thread title when initialsed by files and the message is visible in the report modal in thread

## Acceptance Criteria fulfillment

- [x] Fixed the thread title issue at the time of files
- [x] Report modal contains the message in the thread

Fixes #625

## Video/Screenshots

https://github.com/user-attachments/assets/4335cccc-8d52-43c5-803f-83c00bda03cb

### CODE REVIEW

File: packages/react/src/views/ReportMessage/MessageReportWindow.js [hunk 1]
```diff
@@ -7,9 +7,13 @@ import styles from './ReportMessage.styles';
...
-  const messages = useMessageStore((state) => state.messages);
-  const messageText = messages.filter((message) => message._id === messageId)[0]
-    ?.msg;
+  const messages = useMessageStore((state) => state.messages) || [];
+  const threadMessages = useMessageStore((state) => state.threadMessages) || [];
+  const allMessages = [...messages, ...threadMessages];
+  const messageText = allMessages.filter(
+    (message) => message._id === messageId
+  )[0]?.msg;
+  console.log('messagetext', messageText);
```
Comment (Spiral-Memory) [inline packages/react/src/views/ReportMessage/MessageReportWindow.js:16]: Remove console.log

**Comment by Spiral-Memory** [comment]
Thanks a lot for your contribution @smritidoneria !
