### PR TITLE
Fix for UI Issues with Chat input (Fixes #144)

### LINKED ISSUE #144: Fix UI issues with current input bar
## Description:
This is an extension to the issue #132 to fix some of the issues related to the chat input bar:

### Can't scroll the text within the chat input.
1.  Paste a large amount of text to the input bar.
2. Try scrolling to the top of your input

### Chat box input does not automatically reduce size after user sends message.
1. When you have entered a large message, click enter.

### Full screen version has a scrollbar
1. Go to full screen mode.
2. Focus on chat input
3. Try scrolling

## Expected behavior:
- A) Should be able to scroll the text within the chat input
- B) Should automatically become resized to default chat window size.
- C) Nothing should happen.

### Actual behavior:
 - Currently can't scroll the text within the chat input.
 - Chat box input does not automatically reduce size after user sends message.
 - Full screen version has a scrollbar squashes or expands when we use this scroll bar.

The below displays all 3 issues in order.

https://user-images.githubusercontent.com/80944218/219932482-e9fde3ee-0b67-411a-9d8d-4e0bf788f95f.mp4

### PR DESCRIPTION
**Pull request by SKB231**
# Fix for UI Issues with Chat input

## Acceptance Criteria fulfillment

- [X] Should be able to scroll the text within the chat input when there's a large amount of text.
- [X] Should automatically become resized to default chat window size.
- [X] ChatInput and Header should stick to their place without moving wherever we scroll. 

Fixes #144

## Video:
https://user-images.githubusercontent.com/80944218/222936154-07ffd2af-131e-4f72-baec-874c001a646e.mp4

### CODE REVIEW

**Comment by SKB231** [comment]
Hey @sidmohanty11 Could you review this PR?

File: src/index.js [hunk 1]
```diff
@@ -14,7 +14,7 @@ export const RCComponent = ({
   setClosableState,
   moreOpts = false,
   width = '100%',
-  height = '30vh',
+  height = '50vh',
```
Comment (sidmohanty11) [inline src/index.js:17]: why do we need this change?

File: src/index.js [hunk 2]
```diff
@@ -95,7 +94,12 @@ export const RCComponent = ({
   return (
     <ToastBarProvider>
       <RCInstanceProvider value={{ RCInstance }}>
-        <Box width={width}>
+        <Box
+          width={width}
+          overflowX={'hidden'}
+          overflowY={'hidden'}
+          maxHeight={'100vh'}
```
Comment (sidmohanty11) [inline src/index.js:101]: what are the repercussions of doing this change?

**Review by sidmohanty11 — CHANGES_REQUESTED** [review]
@SKB231 Thanks for the PR!

File: src/index.js (hunk 2 above)
Comment (SKB231) [reply src/index.js:101]: For the maxHeight: (100vh). I set it to this because when we go to full screen mode for the component,  we wouldn't want the input textbox to overflow beneath the window (causing the wierd vertical scrolling issue I mentioned in #144).  Hence, setting it to a max height of 100vh avoids this, and there's no change to the user experience when using the component.

For OverflowX and OverlowY: Since all the content is within the same window and there's no need to scroll any direction, I have set the overflow to hidden (no scrolling). 
Let me know if you'd like to change it back.
I have tested these UI changes in a responsive setting as shown below:

https://user-images.githubusercontent.com/80944218/223284851-61963fdc-c558-4d2e-8edd-02d4988cb938.mp4

File: src/index.js (hunk 1 above)
Comment (SKB231) [reply src/index.js:17]: Screenshot 2023-03-06 185229

For some reason, the recent changes caused the component height of 30 vh to make the chat window look very small, making it hard to conduct debugging, as shown in the screenshot above. So I changed it to 50 vh. Let me know if it's better to keep it at 30vh.

File: src/index.js (hunk 2 above)
Comment (sidmohanty11) [reply src/index.js:101]: Amazing!

File: src/index.js (hunk 1 above)
Comment (sidmohanty11) [reply src/index.js:17]: No lets merge this, we need to think of a better way for making it compact.

**Comment by sidmohanty11** [comment]
@SKB231 PTAL at the conflicts

**Comment by SKB231** [comment]
> @SKB231 PTAL at the conflicts

Done @sidmohanty11 👍

**Review by sidmohanty11 — APPROVED** [review]

**Review by sidmohanty11 — CHANGES_REQUESTED** [review]
Why remove husky?

**Comment by SKB231** [comment]
> Why remove husky?

Done @sidmohanty11 Somehow the files got changed without me realizing. I changed husky back to last commit.

**Review by sidmohanty11 — APPROVED** [review]
